// I Ching — 64 Hexagrams (King Wen sequence)
// Source: Wilhelm-Baynes translation with beginner interpretations

export const HEXAGRAMS = [
  {n:1,name:"Ch'ien",eng:"The Creative",tri:["☰","☰"],judge:"Sublime success. Perseverance furthers.",image:"Heaven above, heaven below. Ceaseless creative force. The sage strengthens himself without rest.",lines:[1,1,1,1,1,1],explain:"This hexagram represents pure creative power — the energy that starts things, drives ambition, and shapes reality. It's telling you that you have tremendous creative potential right now. The key is to use this power wisely and persistently, not recklessly. Think of it like a strong wind at your back — it will carry you far, but only if you hold a steady course."},
  {n:2,name:"K'un",eng:"The Receptive",tri:["☷","☷"],judge:"Sublime success through the perseverance of a mare. The superior one has an undertaking.",image:"Earth above, earth below. The condition of receptive devotion. Boundless capacity.",lines:[0,0,0,0,0,0],explain:"The Receptive is the complement to The Creative — it represents openness, acceptance, and the power of yielding. Rather than forcing things to happen, this hexagram advises you to be like fertile earth: receive what comes, nurture it, and let things grow naturally. Strength here comes from patience and support, not from pushing forward."},
  {n:3,name:"Chun",eng:"Difficulty at the Beginning",tri:["☵","☳"],judge:"Sublime success. Perseverance furthers. Nothing should be undertaken. Appoint helpers.",image:"Water over thunder. Clouds and thunder: the image of difficulty at the beginning.",lines:[1,0,0,0,1,0],explain:"Like a seed pushing through frozen ground, you're in the difficult early stages of something new. This is the chaos that always precedes creation. Don't rush — the oracle advises seeking help and being patient. The difficulty is temporary and natural, like the storm before the clearing."},
  {n:4,name:"Mêng",eng:"Youthful Folly",tri:["☶","☵"],judge:"Success. I do not seek the young fool; the young fool seeks me.",image:"Mountain over water. A spring wells up at the foot of the mountain.",lines:[0,1,0,0,1,0],explain:"This hexagram speaks of inexperience — not as a flaw, but as a starting point. Like a student approaching a teacher, the key is genuine willingness to learn. If you're asking the same question repeatedly hoping for a different answer, the oracle won't respond. Be open, be humble, and accept the lesson."},
  {n:5,name:"Hsü",eng:"Waiting",tri:["☵","☰"],judge:"Sincerity leads to brilliant success. Perseverance brings good fortune. It furthers to cross the great water.",image:"Water over heaven. Clouds rise in the sky: the image of waiting.",lines:[1,1,1,0,1,0],explain:"Rain clouds are gathering but the storm hasn't broken yet. This is a time of necessary waiting — not passive idleness, but active patience. Nourish yourself, prepare, and trust that the right moment will come. Trying to force things now would be like planting seeds in a drought."},
  {n:6,name:"Sung",eng:"Conflict",tri:["☰","☵"],judge:"Sincerity is obstructed. A cautious halt midway brings good fortune. Going through to the end brings misfortune.",image:"Heaven over water. Their motions move in opposite directions.",lines:[0,1,0,1,1,1],explain:"You're in a situation where two forces are pulling in opposite directions. The oracle warns against pushing this conflict to its conclusion. Compromise, mediation, or stepping back is far wiser than fighting to the bitter end. Know when to stop."},
  {n:7,name:"Shih",eng:"The Army",tri:["☷","☵"],judge:"The army needs perseverance and a strong leader. Good fortune without blame.",image:"Water within the earth. The superior one increases his masses by generosity toward the people.",lines:[0,1,0,0,0,0],explain:"Your situation requires disciplined organization and strong leadership — whether that means leading others or marshaling your own inner resources. Success comes through structure, loyalty, and having a clear chain of command."},
  {n:8,name:"Pi",eng:"Holding Together",tri:["☵","☷"],judge:"Holding together brings good fortune. Those who are uncertain gradually join.",image:"Water over earth. Each king of old established states and maintained close relations with the princes.",lines:[0,0,0,0,1,0],explain:"This hexagram is about alliance, unity, and belonging. Water on earth naturally flows together and nourishes everything it touches. The oracle suggests this is a time to build or strengthen your connections with others. But the bond must be genuine — based on shared values, not convenience."},
  {n:9,name:"Hsiao Ch'u",eng:"Small Taming",tri:["☴","☰"],judge:"Dense clouds, no rain from our western territory. Success through gentle restraint.",image:"Wind over heaven. The superior one refines the outward aspect of his nature.",lines:[1,1,1,0,1,1],explain:"You have the power to influence your situation, but only gently — like wind shaping clouds but unable to force them to rain. This is a time for subtle persuasion and small adjustments rather than dramatic moves. The big breakthrough hasn't come yet, but you're preparing the conditions."},
  {n:10,name:"Lü",eng:"Treading",tri:["☰","☱"],judge:"Treading upon the tail of the tiger. It does not bite. Success.",image:"Heaven above, lake below. The superior one discriminates between high and low.",lines:[1,1,0,1,1,1],explain:"You're in a delicate situation — like walking behind a tiger and stepping on its tail. But if you conduct yourself with proper awareness and respect, even dangerous situations can be navigated safely. Be mindful of your behavior and proceed with cheerful confidence despite the danger."},
  {n:11,name:"T'ai",eng:"Peace",tri:["☷","☰"],judge:"The small departs, the great approaches. Good fortune. Success.",image:"Heaven and earth unite: the image of peace. The ruler completes the way of heaven and earth.",lines:[1,1,1,0,0,0],explain:"One of the most auspicious hexagrams. Heaven and earth are in perfect harmony — creative energy flows freely, obstacles dissolve, and there is deep peace and prosperity. This is a golden period. Use it wisely, because all cycles turn — enjoy and build on this good fortune while it lasts."},
  {n:12,name:"P'i",eng:"Standstill",tri:["☰","☷"],judge:"Standstill. Evil people do not further the perseverance of the superior one.",image:"Heaven and earth do not unite: the image of standstill.",lines:[0,0,0,1,1,1],explain:"The opposite of Peace — communication has broken down and things are stagnant. This isn't a time to push forward. Retreat inward, protect your values, and wait. Like winter, this period of standstill is natural and temporary. Don't compromise your integrity to force progress."},
  {n:13,name:"T'ung Jen",eng:"Fellowship",tri:["☰","☲"],judge:"Fellowship in the open. Success. It furthers to cross the great water.",image:"Heaven together with fire. The superior one organizes the clans.",lines:[1,0,1,1,1,1],explain:"True fellowship — people united by shared purpose rather than selfish interest. Genuine community and open cooperation will lead to success, even in great challenges. The key word is 'open' — this fellowship must be inclusive and transparent."},
  {n:14,name:"Ta Yu",eng:"Great Possession",tri:["☲","☰"],judge:"Supreme success.",image:"Fire in heaven above. The superior one curbs evil and furthers good.",lines:[1,1,1,1,0,1],explain:"Fire burning brightly in the heavens — abundance, wealth, and great resources at your disposal. But the oracle's advice is crucial: use this abundance to do good, not to hoard or show off. True greatness in possession means being generous and using your power to further what is right."},
  {n:15,name:"Ch'ien",eng:"Modesty",tri:["☷","☶"],judge:"Modesty creates success. The superior one carries things through.",image:"Within the earth a mountain. The superior one reduces what is too much and augments what is too little.",lines:[0,0,1,0,0,0],explain:"A mountain hidden within the earth — immense strength that doesn't advertise itself. Modesty is not weakness but a form of power. By leveling out imbalances — reducing excess here, adding where there's lack — you create lasting harmony. The modest person completes their work precisely because they don't seek credit."},
  {n:16,name:"Yü",eng:"Enthusiasm",tri:["☳","☷"],judge:"It furthers one to install helpers and to set armies marching.",image:"Thunder comes resounding out of the earth: enthusiasm. The ancient kings made music and honored merit.",lines:[0,0,0,1,0,0],explain:"Thunder erupts from the earth with joyful, irresistible energy. This is the hexagram of inspiration and momentum — when the time is right to rally others, launch projects, and ride the wave of genuine enthusiasm. The key is that this energy must be natural and authentic, not manufactured."},
  {n:17,name:"Sui",eng:"Following",tri:["☱","☳"],judge:"Following has supreme success. Perseverance furthers. No blame.",image:"Thunder within the lake. The superior one at nightfall goes within and rests.",lines:[1,0,0,1,1,0],explain:"Sometimes wisdom means knowing when to follow. This hexagram suggests adapting to the situation, going with the flow, and being willing to follow good guidance rather than always insisting on your own way. Rest when it's time to rest."},
  {n:18,name:"Ku",eng:"Work on the Decayed",tri:["☶","☴"],judge:"Supreme success. It furthers to cross the great water. Before and after the starting point, three days.",image:"Wind at the foot of the mountain. The superior one stirs up the people and strengthens their spirit.",lines:[0,1,1,0,0,1],explain:"Something has been neglected or fallen into decay. This hexagram says it's time to repair what's broken. Take three days to plan, three days after to evaluate. The work is necessary and will lead to great success."},
  {n:19,name:"Lin",eng:"Approach",tri:["☷","☱"],judge:"Approach has supreme success. Perseverance furthers. When the eighth month comes, there is misfortune.",image:"Earth above the lake. The superior one is inexhaustible in teaching and sustaining the people.",lines:[1,1,0,0,0,0],explain:"Good things are approaching — opportunity, growth, progress. But the oracle warns: this favorable period won't last forever. Use this time wisely, teach and support others, and prepare for the inevitable turn of the cycle."},
  {n:20,name:"Kuan",eng:"Contemplation",tri:["☴","☷"],judge:"The ablution has been made, but not yet the offering. Full of trust, they look up.",image:"Wind blows over the earth. The kings of old visited the regions of the world and contemplated the people.",lines:[0,0,0,0,1,1],explain:"Step back and observe. This hexagram asks you to take a wider view of your situation before acting. Contemplation here isn't passive daydreaming — it's the focused, almost sacred act of truly seeing what is, so that when you do act, it comes from deep understanding."},
  {n:21,name:"Shih Ho",eng:"Biting Through",tri:["☲","☳"],judge:"Biting through has success. It is favorable to let justice be administered.",image:"Thunder and lightning: the image of biting through. The kings of old made firm the laws with penalties.",lines:[1,0,0,1,0,1],explain:"Something is blocking progress, like a bone stuck between the teeth. This hexagram says to bite through the obstacle decisively. It often points to a need for clear consequences, firm boundaries, or decisive action. Don't let obstruction persist — deal with it directly."},
  {n:22,name:"Pi",eng:"Grace",tri:["☶","☲"],judge:"Grace has success. In small matters it is favorable to undertake something.",image:"Fire at the foot of the mountain. The superior one clarifies current affairs without daring to decide lawsuits.",lines:[1,0,1,0,0,1],explain:"Beauty, form, and elegance — but this hexagram reminds you that grace is the finishing touch, not the substance. This is a good time for small, refined actions — polishing, beautifying, presenting well — but not for making major decisions based on appearances alone."},
  {n:23,name:"Po",eng:"Splitting Apart",tri:["☶","☷"],judge:"Splitting apart. It does not further to go anywhere.",image:"Mountain resting on the earth. Those above ensure their position by giving generously to those below.",lines:[0,0,0,0,0,1],explain:"The foundation is eroding. This is not the time to act or push forward — accept the natural dissolution and give generously. What splits apart now will reform later in a better configuration. Sometimes things must collapse before they can be rebuilt."},
  {n:24,name:"Fu",eng:"Return",tri:["☷","☳"],judge:"Return. Success. Going out and coming in without error. Companions come without blame.",image:"Thunder within the earth. The kings of old closed the passes at the time of solstice.",lines:[1,0,0,0,0,0],explain:"After the darkest point, the first light returns. This hexagram marks a turning point — the seed of new growth appearing after a period of decline. Like the winter solstice, when days begin to grow longer again. Don't rush this renewal. Let it build naturally."},
  {n:25,name:"Wu Wang",eng:"Innocence",tri:["☰","☳"],judge:"Supreme success. Perseverance furthers. If someone is not as they should be, misfortune.",image:"Under heaven, thunder rolls. All things attain the natural state of innocence.",lines:[1,0,0,1,1,1],explain:"Act from your true nature, without calculation or ulterior motives. This hexagram represents the power of genuine, innocent action — doing what's right simply because it's right. If you're scheming or being dishonest (even with yourself), the oracle warns of misfortune."},
  {n:26,name:"Ta Ch'u",eng:"Great Taming",tri:["☶","☰"],judge:"Perseverance furthers. Not eating at home brings good fortune. It furthers to cross the great water.",image:"Heaven within the mountain. The superior one acquaints themselves with many sayings of antiquity.",lines:[1,1,1,0,0,1],explain:"Tremendous creative energy is being held in check. This is a time of building inner strength, studying wisdom, and accumulating power for a future breakthrough. You have stored enough energy to succeed at big undertakings."},
  {n:27,name:"I",eng:"Nourishment",tri:["☶","☳"],judge:"Perseverance brings good fortune. Pay heed to the providing of nourishment.",image:"At the foot of the mountain, thunder. The superior one is careful of words and temperate in eating and drinking.",lines:[1,0,0,0,0,1],explain:"What are you feeding — your body, your mind, your spirit? This hexagram asks you to examine both what you consume and what you give to others. Are your words nourishing or toxic? Pay attention to the quality of your input and output in all areas of life."},
  {n:28,name:"Ta Kuo",eng:"Great Excess",tri:["☱","☴"],judge:"The ridgepole sags. It furthers to have somewhere to go. Success.",image:"The lake rises above the trees. The superior one stands alone without fear.",lines:[0,1,1,1,1,0],explain:"The load is too heavy — the central beam is bending. Something in your life has become excessive or unsustainable. Don't panic, but do act: redistribute the weight or move to a new position entirely. Courage and independence are needed now."},
  {n:29,name:"K'an",eng:"The Abysmal",tri:["☵","☵"],judge:"Repetition of the abysmal. Sincerity in the heart leads to success.",image:"Water flows on, reaching the goal: the image of the abyss repeated.",lines:[0,1,0,0,1,0],explain:"Danger upon danger — like being caught in rapids. But water teaches us the way through: it flows with absolute sincerity and consistency. You're in real danger, but if you stay true to your inner values and keep moving forward honestly, you will find your way through. Don't try to escape — flow through."},
  {n:30,name:"Li",eng:"The Clinging",tri:["☲","☲"],judge:"The clinging. Perseverance furthers. Success. Care of the cow brings good fortune.",image:"Brightness rises twice: the image of fire. The great one illuminates the four quarters.",lines:[1,0,1,1,0,1],explain:"Fire clings to its fuel to burn — it depends on something outside itself. This hexagram is about interdependence, clarity, and illumination. You need something to attach to: a purpose, a discipline, a relationship. Through this attachment, you gain brilliance."},
  {n:31,name:"Hsien",eng:"Influence",tri:["☱","☶"],judge:"Success. Perseverance furthers. To take a maiden to wife brings good fortune.",image:"A lake on the mountain. The superior one encourages people to approach through receptiveness.",lines:[0,0,1,1,1,0],explain:"Mutual attraction, influence, and connection. This hexagram describes the power of genuine openness to attract and influence others. In relationships, it speaks of natural chemistry and mutual responsiveness. Be open, be receptive, and let the connection form naturally."},
  {n:32,name:"Hêng",eng:"Duration",tri:["☳","☴"],judge:"Success. No blame. Perseverance furthers. It furthers to have somewhere to go.",image:"Thunder and wind: the image of duration. The superior one stands firm without changing direction.",lines:[0,1,1,1,0,0],explain:"Thunder and wind reinforce each other endlessly. This hexagram is about commitment, consistency, and the long game. Stay the course. True duration isn't rigid stubbornness — it's the ability to remain constant in your direction while being flexible in your methods."},
  {n:33,name:"Tun",eng:"Retreat",tri:["☰","☶"],judge:"Retreat. Success. In what is small, perseverance furthers.",image:"Mountain under heaven. The superior one keeps the inferior at a distance.",lines:[0,0,1,1,1,1],explain:"Strategic withdrawal, not cowardly escape. There are times when retreating is the strongest possible move. Pull back with dignity, maintain your boundaries, and don't waste energy engaging with what drags you down. Retreat now to advance later."},
  {n:34,name:"Ta Chuang",eng:"Great Power",tri:["☳","☰"],judge:"Perseverance furthers.",image:"Thunder in heaven above. The superior one does not tread paths not in accord with established order.",lines:[1,1,1,1,0,0],explain:"You have great power right now — the question is how you use it. Thunder rolling across the heavens is mighty but follows natural law. Power + righteousness = true greatness. Power + ego = inevitable downfall."},
  {n:35,name:"Chin",eng:"Progress",tri:["☲","☷"],judge:"The powerful prince is honored with horses in large numbers.",image:"The sun rises over the earth. The superior one brightens their bright virtue.",lines:[0,0,0,1,0,1],explain:"The sun rising over the earth — clear, unstoppable, illuminating everything. This is a time of rapid, natural progress. You're being recognized and given resources. Let your inner light shine honestly as the sun does."},
  {n:36,name:"Ming I",eng:"Darkening of the Light",tri:["☷","☲"],judge:"In adversity it furthers to be persevering.",image:"The light has sunk into the earth. The superior one veils their light yet still shines.",lines:[1,0,1,0,0,0],explain:"The sun has gone below the earth — your brilliance must be hidden for now. This hexagram appears when showing your true nature would be dangerous. Like an ember buried in ash, keep your inner fire alive but concealed. The darkness will pass."},
  {n:37,name:"Chia Jen",eng:"The Family",tri:["☴","☲"],judge:"The perseverance of the woman furthers.",image:"Wind coming from fire. The superior one has substance in words and duration in conduct.",lines:[1,0,1,0,1,1],explain:"This hexagram is about the home, family, and your inner circle. It speaks to the importance of right relationships, clear roles, and genuine warmth within your closest bonds."},
  {n:38,name:"K'uei",eng:"Opposition",tri:["☲","☱"],judge:"In small matters, good fortune.",image:"Fire above, the lake below. The superior one retains individuality amid community.",lines:[1,1,0,1,0,1],explain:"Fire rises, water sinks — they move in opposite directions. You're dealing with opposing forces or conflicting perspectives. But opposition isn't always bad. Small things can still succeed even amid major disagreements. Maintain your individuality while finding common ground."},
  {n:39,name:"Chien",eng:"Obstruction",tri:["☵","☶"],judge:"The southwest furthers. The northeast does not further. Perseverance: good fortune.",image:"Water on the mountain. The superior one turns attention to oneself and molds character.",lines:[0,0,1,0,1,0],explain:"An obstacle blocks your path. Don't charge forward. Instead, turn inward and use this blockage as an opportunity for self-improvement. Seek wise counsel. The obstacle is redirecting you toward the path you should actually be on."},
  {n:40,name:"Hsieh",eng:"Deliverance",tri:["☳","☵"],judge:"The southwest furthers. If there is no longer anything to be gained, return brings good fortune.",image:"Thunder and rain set in. The superior one pardons mistakes and forgives misdeeds.",lines:[0,1,0,1,0,0],explain:"The storm has broken and tension is released. The obstacle or danger has passed. Now is the time for forgiveness, fresh starts, and moving on quickly. Don't linger in what went wrong. Return to normal life and let go of grudges."},
  {n:41,name:"Sun",eng:"Decrease",tri:["☶","☱"],judge:"Decrease combined with sincerity brings supreme good fortune.",image:"At the foot of the mountain, the lake. The superior one controls anger and restrains the instincts.",lines:[1,1,0,0,0,1],explain:"Sometimes you must give something up to gain something greater. This hexagram asks: what are you willing to sacrifice? If your decrease is sincere and purposeful, it leads to supreme good fortune. Restraining excess is a form of increase."},
  {n:42,name:"I",eng:"Increase",tri:["☴","☳"],judge:"It furthers to undertake something. It furthers to cross the great water.",image:"Wind and thunder: the image of increase. The superior one furthers improvement without limits.",lines:[1,0,0,0,1,1],explain:"Now is a time of genuine increase and expansion. Wind and thunder amplify each other. Take on big projects, push your limits. When you see something good, adopt it. When you see a flaw in yourself, correct it. Use this energy boldly."},
  {n:43,name:"Kuai",eng:"Breakthrough",tri:["☱","☰"],judge:"One must resolutely make the matter known at the court. Danger.",image:"The lake has risen up to heaven. The superior one dispenses riches downward.",lines:[1,1,1,1,1,0],explain:"The floodwaters have risen to the breaking point. Something must give — a truth must be spoken, a corrupt element must be removed. The breakthrough must be made through openness and generosity, not through violence or self-righteous fury."},
  {n:44,name:"Kou",eng:"Coming to Meet",tri:["☰","☴"],judge:"The maiden is powerful. One should not marry such a maiden.",image:"Under heaven, wind. The prince disseminates commands to the four quarters.",lines:[0,1,1,1,1,1],explain:"Something unexpected has appeared — perhaps a temptation or influence that seems harmless but carries hidden power. This hexagram warns against being seduced by what seems insignificant. Stay alert to subtle, creeping influences that could gradually take over."},
  {n:45,name:"Ts'ui",eng:"Gathering Together",tri:["☱","☷"],judge:"Success. The king approaches his temple. It furthers to see the great one.",image:"Over the earth, the lake. The superior one renews their weapons to meet the unforeseen.",lines:[0,0,0,1,1,0],explain:"People are gathering for a shared purpose. This hexagram speaks of the power of assembly and the importance of having a central principle around which people can unite. But whenever people gather, prepare for the unexpected."},
  {n:46,name:"Shêng",eng:"Pushing Upward",tri:["☷","☴"],judge:"Pushing upward has supreme success. One must see the great one. Fear not.",image:"Within the earth, wood grows. The superior one accumulates small things to achieve something great.",lines:[0,1,1,0,0,0],explain:"A tree growing through the earth toward the light — steady, determined upward growth. This is gradual ascent through persistent effort. Each small step builds on the last. Don't be afraid. Your consistent effort will carry you to heights you can't yet see."},
  {n:47,name:"K'un",eng:"Oppression",tri:["☱","☵"],judge:"Success. Perseverance. The great one brings good fortune. When one has something to say, it is not believed.",image:"There is no water in the lake. The superior one stakes their life on following their will.",lines:[0,1,0,1,1,0],explain:"The lake has dried up — you're exhausted, confined, or oppressed. Words won't help because no one believes you right now. But the oracle still says 'success' — because your response to adversity defines you. Stay true to your purpose even when all external support has dried up."},
  {n:48,name:"Ching",eng:"The Well",tri:["☵","☴"],judge:"The town may be changed, but not the well. It neither decreases nor increases.",image:"Water over wood: the image of the well. The superior one encourages people to help one another.",lines:[0,1,1,0,1,0],explain:"The well is the unchanging source — while everything around it changes, it remains constant. This hexagram points to your deep, inner source of wisdom. Are you drawing from it? Or has the rope become too short? Repair your connection to your own deepest truth."},
  {n:49,name:"Ko",eng:"Revolution",tri:["☱","☲"],judge:"On your own day you are believed. Supreme success. Remorse disappears.",image:"Fire in the lake. The superior one sets the calendar in order.",lines:[1,0,1,1,1,0],explain:"Fire and water in direct conflict — something fundamental must change. Revolution must come at the right time, for the right reasons, and with the trust of others. When the time is truly right, act with conviction and all regret will vanish."},
  {n:50,name:"Ting",eng:"The Cauldron",tri:["☲","☴"],judge:"Supreme good fortune. Success.",image:"Fire over wood: the image of the cauldron. The superior one consolidates fate.",lines:[0,1,1,1,0,1],explain:"The cauldron was the most sacred vessel in ancient China — used to cook offerings for the divine. You're being called to take what you have and transform it into something of real spiritual and practical value. Supreme good fortune."},
  {n:51,name:"Chên",eng:"The Arousing",tri:["☳","☳"],judge:"Shock brings success. Shock comes — oh, oh! Laughing words — ha, ha!",image:"Thunder repeated: the image of shock. The superior one through anxiety sets life in order.",lines:[1,0,0,1,0,0],explain:"BOOM — thunder upon thunder. A sudden shock that terrifies but ultimately awakens. Those who meet the shock with composure and even humor will find it leads to success. Use the adrenaline to reorganize your life."},
  {n:52,name:"Kên",eng:"Keeping Still",tri:["☶","☶"],judge:"Keeping the back still so that one no longer feels the body. No blame.",image:"Mountains standing close together. The superior one does not permit thoughts to go beyond the situation.",lines:[0,0,1,0,0,1],explain:"Absolute stillness — meditation, rest, cessation of movement. This hexagram says: stop. Stop moving, stop thinking beyond your immediate situation. In this perfect stillness, the restless mind quiets and clarity emerges. This is the I Ching's most direct instruction to meditate."},
  {n:53,name:"Chien",eng:"Development",tri:["☴","☶"],judge:"The maiden is given in marriage. Good fortune. Perseverance furthers.",image:"On the mountain, a tree. The superior one abides in dignity and virtue.",lines:[0,0,1,0,1,1],explain:"A tree growing on a mountain — slow, gradual, but inexorable development. Your situation is developing at exactly the right pace. Don't try to skip steps. Each stage must be completed properly before moving to the next."},
  {n:54,name:"Kuei Mei",eng:"The Marrying Maiden",tri:["☳","☱"],judge:"Undertakings bring misfortune. Nothing that would further.",image:"Thunder over the lake. The superior one understands the transitory in the light of the eternal.",lines:[1,1,0,1,0,0],explain:"A difficult hexagram — it describes being in a subordinate or compromised position. The oracle bluntly says: undertakings bring misfortune right now. Make the best of an imperfect situation while maintaining awareness that all conditions are temporary."},
  {n:55,name:"Fêng",eng:"Abundance",tri:["☳","☲"],judge:"Abundance has success. The king attains abundance. Be not sad. Be like the sun at midday.",image:"Both thunder and lightning come. The superior one decides lawsuits and carries out punishments.",lines:[1,0,1,1,0,0],explain:"Absolute peak — like the sun at high noon. This is a moment of tremendous abundance and success. But midday is also when the sun begins to descend. Don't be sad. Enjoy the fullness and use this peak of clarity to make important decisions."},
  {n:56,name:"Lü",eng:"The Wanderer",tri:["☲","☶"],judge:"Success through smallness. Perseverance brings good fortune to the wanderer.",image:"Fire on the mountain. The superior one is clear-minded and cautious.",lines:[0,0,1,1,0,1],explain:"You're a stranger in a strange land — passing through, not settled. Success comes through being modest, careful, and not overstepping your welcome. Travel light. Don't get entangled. Move through with grace and awareness."},
  {n:57,name:"Sun",eng:"The Gentle",tri:["☴","☴"],judge:"The gentle. Success through what is small. It furthers to see the great one.",image:"Winds following one upon the other. The superior one spreads commands abroad.",lines:[0,1,1,0,1,1],explain:"Wind upon wind — gentle, persistent penetration. The softest force, applied consistently, achieves what brute strength cannot. Have a clear direction, then advance softly but steadily."},
  {n:58,name:"Tui",eng:"The Joyous",tri:["☱","☱"],judge:"The joyous. Success. Perseverance is favorable.",image:"Lakes resting one on the other. The superior one joins with friends for discussion.",lines:[1,1,0,1,1,0],explain:"Pure joy — two lakes connected, sharing their waters. This hexagram celebrates genuine happiness, friendship, and open communication. True joy is not frivolous pleasure but deep, sustained gladness from inner strength and good company."},
  {n:59,name:"Huan",eng:"Dispersion",tri:["☴","☵"],judge:"Success. The king approaches his temple. It furthers to cross the great water.",image:"Wind blows over water. The kings of old sacrificed to the Lord and built temples.",lines:[0,1,0,0,1,1],explain:"Wind scattering water — dissolving what has hardened, breaking up rigid patterns. The remedy is spiritual or communal: reconnecting with something larger than yourself. When the heart thaws, the ice breaks and the river flows again."},
  {n:60,name:"Chieh",eng:"Limitation",tri:["☵","☱"],judge:"Success. Galling limitation must not be persevered in.",image:"Water over lake. The superior one creates number and measure.",lines:[1,1,0,0,1,0],explain:"Boundaries, limits, structure — like the banks that give a river its direction. Healthy limitations create the structure for success. But limitation that becomes oppressive defeats its own purpose. Set boundaries, but don't make them into prisons."},
  {n:61,name:"Chung Fu",eng:"Inner Truth",tri:["☴","☱"],judge:"Inner truth. Pigs and fishes. Good fortune. It furthers to cross the great water.",image:"Wind over lake. The superior one discusses criminal cases in order to delay executions.",lines:[1,1,0,0,1,1],explain:"The most difficult creatures to influence — pigs and fish — can be reached by inner truth. This hexagram describes sincerity so deep and authentic that it moves even the most resistant beings. This is the power of integrity: real alignment between your inner and outer self."},
  {n:62,name:"Hsiao Kuo",eng:"Small Excess",tri:["☳","☶"],judge:"Small excess. Success. Small things may be done; great things should not be done.",image:"Thunder on the mountain. The superior one gives excess to reverence and frugality.",lines:[0,0,1,1,0,0],explain:"A bird in flight — it can go a little too high, but not much. Exceed in small things (extra care, extra modesty, extra detail) while not attempting anything too ambitious. A time for caution and humility."},
  {n:63,name:"Chi Chi",eng:"After Completion",tri:["☵","☲"],judge:"Success in small matters. Good fortune at the beginning, disorder at the end.",image:"Water over fire. The superior one takes thought of misfortune and arms against it.",lines:[1,0,1,0,1,0],explain:"Everything is in its right place — the task is complete. But paradoxically, this is one of the most dangerous moments. After completion, the only direction is toward disorder. Don't become complacent. Prepare now for the challenges that follow success."},
  {n:64,name:"Wei Chi",eng:"Before Completion",tri:["☲","☵"],judge:"Success. But if the little fox gets its tail in the water, there is nothing that would further.",image:"Fire over water. The superior one carefully discriminates among things.",lines:[0,1,0,1,0,1],explain:"The final hexagram — nothing is ever truly 'complete.' You're almost across the river, but the last steps are the most dangerous. Every ending is really a new beginning. Stay focused until the very end. The cycle continues."},
];


export function throwCoins() {
  const coins = [0,1,2].map(() => Math.random() < 0.5 ? 3 : 2);
  const sum = coins[0]+coins[1]+coins[2];
  return { coins, sum, yang: sum===7||sum===9, changing: sum===6||sum===9,
    lineType: sum===6?"old_yin":sum===7?"young_yang":sum===8?"young_yin":"old_yang" };
}

export function lookupHexagram(lines) {
  const pattern = lines.map(l => l.yang ? 1 : 0);
  return HEXAGRAMS.find(h =>
    h.lines[0]===pattern[0]&&h.lines[1]===pattern[1]&&h.lines[2]===pattern[2]&&
    h.lines[3]===pattern[3]&&h.lines[4]===pattern[4]&&h.lines[5]===pattern[5]
  ) || HEXAGRAMS[0];
}
